### ISSUE TITLE
Switch to pre-commit.ci

### ISSUE THREAD

**Issue by ns-rse** [claritychallenge/clarity#166]
Currently there is a `pre-commit` GitHub Action in place which runs `pre-commit` against Pull Requests. However this sometimes fails if code hasn't been linted correctly locally first (see [example](https://github.com/claritychallenge/clarity/actions/runs/3911430678/jobs/6684813513)).

One way of getting around this is to use [pre-commit.ci](https://pre-commit.ci) which can be configured to commit and make the changes to the Pull Request directly (e.g. if `black` is applied to code).

This shortens the feedback loop and lessens the burden on contributors.

**Comment by slackline** [comment]
As an example #161 failed the linting because `black` found errors (see [run](https://github.com/claritychallenge/clarity/actions/runs/3911430678/jobs/6684813513#step:5:73)).

[pre-commit.ci](https://pre-commit.ci) will be default make a commit and push to the pull request automatically when such changes are made.

**Comment by ns-rse** [comment]
As an example #161 failed the linting because `black` found errors (see [run](https://github.com/claritychallenge/clarity/actions/runs/3911430678/jobs/6684813513#step:5:73)).

[pre-commit.ci](https://pre-commit.ci) will be default make a commit and push to the pull request automatically when such changes are made.
