### ISSUE TITLE
Contribution Guidelines for clarity

### ISSUE THREAD

**Issue by ns-rse** [claritychallenge/clarity#17]
It is useful to have [contribution guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) for projects so that participants know what is expected of them when they consider contributing to the code base.

**Comment by jonbarker68** [comment]
@ns-rse  These guidelines look great but does it need to be CONTRIBUTING.md for GitHub's autodetect features to work, or is contributing.md also OK?

The documentation here has it in uppercase: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

Also, would it be better to then to move CODE_OF_CONDUCT.md from the root folder into docs, so that these 'community health' files are all in the same place. GitHub seems to all them to be either in the root, in docs/ or in .github. Putting them in docs/ seems most logical.
