### ISSUE TITLE
Randomness in HASPI

### ISSUE THREAD

**Issue by YoshikiMas** [claritychallenge/clarity#7]
Hi everyone,

Let me thank the organizers for this fantastic and interesting challenge!

When I check the scripts for calculating HASPI, I find some randomness in [eb](https://github.com/claritychallenge/clarity/blob/c07318f67a14d37cefd0619f68508d5618319c00/clarity/evaluator/haspi/eb.py#L831) and [ebm](https://github.com/claritychallenge/clarity/blob/c07318f67a14d37cefd0619f68508d5618319c00/clarity/evaluator/haspi/ebm.py#L162). As a result, the score for the same signals slightly fluctuated in some runs. Although the fluctuation is very small, it will be good to fix the seed.

Probably, I misunderstand something. Please check whether the fluctuation occurs in your environment. Thank you!

**Comment by jwillbailey** [comment]
Hi Yoshiki

Thank you for your question.

Randomness is intrinsic to HASPI because of the acoustic noise added to simulate the threshold of hearing. However, for validation purposes, we will be releasing a 
version of the tools with an optional fixed seed in the near future. We need to make sure that any approach we use gives consistency on single threaded and multithreaded systems and this is not ready yet.
 
In the mean time, performing multiple runs on individual signals and generating mean and variance values to check the consistency of results. According to our testing, the HASPI score for a given signal may vary with 50% of samples varying between ±0.0004 and ±0.0008 across runs. This is normal and is due to the fact the HASPI algorithm uses randomly generated internal noise in its computation.

Many thanks

Will
