### ISSUE TITLE
Different length for audio files and head rotation signal

### ISSUE THREAD

**Issue by Chengwei-Ouyang** [claritychallenge/clarity#8]
Hi,

Thanks for your fantastic works!

I'm trying to use the head rotation signal, but I find that the length of the audio files (e.g. mixed_CH1.wav, target_CH1.wav) and head rotation file (hr.wav) is different. The head rotation signal is 255 points shorter than audio files. For example, S06001 in dev dataset, the length of S06001_hr.wav is 287735 and the length of S06001_mix_CH0.wav is 287990.

My question is how should I deal with the misalignment, should I neglect 255 points in the beginning or the end of the audio files？

Best regards,

Chengwei Ouyang

**Comment by jonbarker68** [comment]
Hi Chengwei,  we're looking at this and will get back to you. Note, given the speed of the head turn, a 255 sample (~5 ms) alignment difference will be a very small angle - but we'll get back to you with an answer shortly so that this can be treated consistently. Jon

**Comment by Chengwei-Ouyang** [comment]
Thanks for your reply. I had tried to align the hr.wav file with audio files by both ways (neglect 255 points in the beginning or the end of audio files), and neglecting 255 points in the beginning performs better. However, the experiment is not rigorous enough, and I'm looking forward to your further confirmation. Thank you!

**Comment by jwillbailey** [comment]
Hi Chengwei,

What you are seeing is an effect of the binaural rendering. The head rotation vector is generated at the same times as the ambisonic audio which is used as a mid-stage in the processing for the scene rendering (please see the function generate_hoa_signals(self, scene) within [scene_renderer_cec2.py](https://github.com/claritychallenge/clarity/blob/main/clarity/data/scene_renderer_cec2.py).

The ambisonic audio isn't saved to disk but is rendered using generate_binaural_signals().

The HRTFs that we use have a kernel size of 256. The 255 sample difference in length that you're observing is a property of the convolution operation. The length of the output of a convolution is:

len(conv(A,B)) == len(A) + len(B) - 1

In this case, you can just remove/ignore the last 255 samples of the audio.

Due to the nature of the impulse responses used, there is a group delay and interaural delay associated with these filters. However, these will be very small (by definition, no longer than the kernel length) and an intrinsic property of the kind of signal processing used.

 If you have any other queries relating to this issue, please get in touch.

Will

**Comment by Chengwei-Ouyang** [comment]
Thanks for your patient! I think it solved my problem.
